# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1290129909);
user_pref("app.update.lastUpdateTime.background-update-timer", 1290129838);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1290130048);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1290129851);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1290129263);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1290129331);
user_pref("browser.migration.version", 1);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.selectedEngine", "红杏搜索");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage", "chrome://speeddial/content/speeddial.xul");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.12");
user_pref("browser.warnOnRestart", false);
user_pref("extensions.autoproxy.currentVersion", "0.3b4.0+.2009110800");
user_pref("extensions.dta.version", "1.1");
user_pref("extensions.enabledItems", "moonlight@novell.com:2.3,{64161300-e22b-11db-8314-0800200c9a66}:0.9.5.6,{e4a8a97b-f2ed-450b-b12d-ee082ba24781}:0.8.20100408.6,{D644F7E7-5141-4fac-A59C-21101C82C734}:0.4.4,{473f9a20-ce5a-11da-a94d-0800200c9a66}:0.6,{02450954-cdd9-410f-b1da-db804e18c671}:0.96.3,{DDC359D1-844A-42a7-9AA1-88A850A938A8}:1.1.10,autoproxy@autoproxy.org:0.3b4.0+.2009110800,{e0204bd5-9d31-402b-a99d-a6aa8ffebdca}:1.2.5,fwall.info@gmail.com:0.30,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.12,{00352F14-3F76-4e4d-ACFF-9976D7E4B3B9}:0.6.8");
user_pref("extensions.lastAppVersion", "3.6.12");
user_pref("extensions.newAddons", "fwall.info@gmail.com");
user_pref("extensions.speeddial.currentVersion", "0.9.5.6");
user_pref("extensions.speeddial.group-1-columns", 3);
user_pref("extensions.speeddial.group-1-rows", 3);
user_pref("extensions.speeddial.loadInNewTab", true);
user_pref("extensions.speeddial.maximumWidth", 1200);
user_pref("extensions.speeddial.thumbnail-1-cropping", "0,0,240,60,150");
user_pref("extensions.speeddial.thumbnail-1-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-1-extra", "Guangzhou,%20Guangdong#C#cloudy#Guangzhou,%20Guangdong");
user_pref("extensions.speeddial.thumbnail-1-format", "png");
user_pref("extensions.speeddial.thumbnail-1-icon", "data:");
user_pref("extensions.speeddial.thumbnail-1-js", false);
user_pref("extensions.speeddial.thumbnail-1-label", "Cloudy, 18°C 在 Guangzhou, Guangdong");
user_pref("extensions.speeddial.thumbnail-1-lastsaved", "1290129279955");
user_pref("extensions.speeddial.thumbnail-1-layout", 3);
user_pref("extensions.speeddial.thumbnail-1-refreshinterval", 1800);
user_pref("extensions.speeddial.thumbnail-1-url", "weather:Guangzhou");
user_pref("extensions.speeddial.thumbnail-2-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-2-format", "png");
user_pref("extensions.speeddial.thumbnail-2-js", false);
user_pref("extensions.speeddial.thumbnail-2-label", "archlive - Project Hosting on Google Code");
user_pref("extensions.speeddial.thumbnail-2-lastsaved", "1290129315853");
user_pref("extensions.speeddial.thumbnail-2-refreshinterval", 86400);
user_pref("extensions.speeddial.thumbnail-2-url", "http://archlive.googlecode.com");
user_pref("extensions.speeddial.thumbnail-3-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-3-format", "png");
user_pref("extensions.speeddial.thumbnail-3-js", false);
user_pref("extensions.speeddial.thumbnail-3-label", "Chatterous | Archlive");
user_pref("extensions.speeddial.thumbnail-3-lastsaved", "1290129380836");
user_pref("extensions.speeddial.thumbnail-3-refreshinterval", 86400);
user_pref("extensions.speeddial.thumbnail-3-url", "http://www.chatterous.com/archlive/");
user_pref("extensions.speeddial.thumbnail-4-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-4-format", "png");
user_pref("extensions.speeddial.thumbnail-4-js", false);
user_pref("extensions.speeddial.thumbnail-4-label", "LinuxTOY");
user_pref("extensions.speeddial.thumbnail-4-lastsaved", "1290129409372");
user_pref("extensions.speeddial.thumbnail-4-refreshinterval", 86400);
user_pref("extensions.speeddial.thumbnail-4-url", "http://linuxtoy.org");
user_pref("extensions.speeddial.thumbnail-5-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-5-format", "png");
user_pref("extensions.speeddial.thumbnail-5-js", false);
user_pref("extensions.speeddial.thumbnail-5-label", "LinuxSir.Org - Powered By LinuxSir");
user_pref("extensions.speeddial.thumbnail-5-lastsaved", "1290129423729");
user_pref("extensions.speeddial.thumbnail-5-refreshinterval", 86400);
user_pref("extensions.speeddial.thumbnail-5-url", "http://www.linuxsir.org/bbs");
user_pref("extensions.speeddial.thumbnail-6-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-6-format", "png");
user_pref("extensions.speeddial.thumbnail-6-js", false);
user_pref("extensions.speeddial.thumbnail-6-label", "运维专家网论坛 - Powered by Discuz!");
user_pref("extensions.speeddial.thumbnail-6-lastsaved", "1290129438890");
user_pref("extensions.speeddial.thumbnail-6-refreshinterval", 86400);
user_pref("extensions.speeddial.thumbnail-6-url", "http://bbs.linuxtone.org");
user_pref("extensions.speeddial.thumbnail-8-dynamictitle", true);
user_pref("extensions.speeddial.thumbnail-8-format", "png");
user_pref("extensions.speeddial.thumbnail-8-js", false);
user_pref("extensions.speeddial.thumbnail-8-label", "Google");
user_pref("extensions.speeddial.thumbnail-8-lastsaved", "1290129474304");
user_pref("extensions.speeddial.thumbnail-8-refreshinterval", 86400);
user_pref("extensions.speeddial.thumbnail-8-url", "http://www.google.com.hk/");
user_pref("extensions.speeddial.widthModifier", 80);
user_pref("extensions.torbutton.fresh_install", false);
user_pref("extensions.torbutton.http_port", 8118);
user_pref("extensions.torbutton.http_proxy", "127.0.0.1");
user_pref("extensions.torbutton.https_port", 8118);
user_pref("extensions.torbutton.https_proxy", "127.0.0.1");
user_pref("extensions.torbutton.normal_exit", true);
user_pref("extensions.torbutton.socks_host", "127.0.0.1");
user_pref("extensions.torbutton.socks_port", 9050);
user_pref("extensions.torbutton.startup", true);
user_pref("extensions.torbutton.tz_string", "CST-08:00");
user_pref("extensions.update.notifyUser", false);
user_pref("gbookmarks.version", "0.6");
user_pref("greasemonkey.version", "0.8.20100408.6");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1292721252);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
