#!/bin/bash

#
# This script support some ZenLive's cheatcodes.
#

. /etc/rc.d/functions
. /etc/rc.d/functions.d/cmdline
. /usr/lib/liblinuxlive

# 需要自己重新设置root用户密码在内核参数加上 passwd=ask
newrootpass="`cmdline_value passwd`"
if [ "$newrootpass" = "ask" ]; then
    echo -ne "\n请输入root用户新密码: "
    read -s newrootpass
fi

if [ ! "$newrootpass" = "" ]; then
    echo "root:$newrootpass" | /usr/sbin/chpasswd
fi

AUTOCMD=$(cmdline_value "autoexec" | tr "~" " ")
if [ "$AUTOCMD" != "" ]; then
   echo "正在自动执行命令: su --login -c \"$AUTOCMD\""
   su --login -c "$AUTOCMD"
fi

# 新模块加入时在内核参数中加入 ldconfig
if [ "`cmdline_parameter ldconfig`" ]; then  
    [[ -x /sbin/ldconfig ]] && /sbin/ldconfig
fi

generate_initial_config() {
		stat_busy "正在初始化 /etc/X11/xorg.conf"
		sleep 3
		#LANG=C /usr/bin/Xorg -configure > /tmp/xorg_detection.log 2>&1
		#mv /xorg.conf.new /etc/X11/xorg.conf
cat <<EOF >> /etc/X11/xorg.conf
Section "Extensions"
	Option "Composite" "Enable"
	Option "RENDER" "Enable"
EndSection

Section "ServerFlags"
	Option	"DontZap" "false"
	Option 	 "AllowMouseOpenFail"  "true"	
 	Option 	 "AutoAddDevices" "true"
EndSection

EOF
		stat_done
}

# 如果不想启动X，在内核参数加入 noxconf
if [ ! "`cmdline_parameter noxconf`" ]; then
	if [ "`cmdline_parameter nonfree`" ]; then
		if [ -e "/etc/X11/xorg.conf" ]; then
    			/etc/rc.d/xakra-nonfree start
		else
			/etc/rc.d/xakra start
    			/etc/rc.d/xakra-nonfree start
		fi
	elif [ ! -e "/etc/X11/xorg.conf" ]; then
		generate_initial_config
	fi
fi

# lang: 重新设置语言
lang="`cmdline_value lang`"
if [ "$lang" ]; then
    locale-gen
fi

# keyb: 重新设置键盘布局
keyb="`cmdline_value keyb`"
if [ "$keyb" ]; then
   if [ -x /bin/loadkeys ]; then
 	/bin/loadkeys $keyb
   fi
fi

# 如果想登入你想要的桌面环境，加入相应内核参数，比如"session=fvwm2" 
session="`cmdline_value session`"
if [ "$session" != "" ]; then
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/X11/xinit/xinitrc
	cp -af "/etc/X11/xinit/xinitrc.${session}" /etc/skel/.xinitrc
fi

chmod 0440 /etc/sudoers

if [ "x$(cmdline_parameter root)" = "x" ]; then
	if [ -x /usr/bin/update-desktop-database ]; then
		update-desktop-database -q
	fi
fi

chown arch:users -R /home/arch
chown root:root -R /root

a8tc=$(cmdline_parameter a8tc)
if [ "$a8tc" ]; then
#	/etc/rc.d/asus-a8tc #太慢
   if [ -f /etc/modprobe.d/modprobe.conf ]; then
	if [ "x$(grep "options snd-hda-intel model=6stack" /etc/modprobe.d/modprobe.conf)" = "x" ]; then
            echo "options snd-hda-intel model=6stack" > /etc/modprobe.d/modprobe.conf
        fi
   else
      cat <<EOF >> /etc/modprobe.d/modprobe.conf
options snd-hda-intel model=6stack
EOF
   fi
fi