#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/crond`
case "$1" in
  start)
    stat_busy "正在启动 Cron 后台服务"
    [ -z "$PID" ] && /usr/sbin/crond >>/var/log/crond 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/sbin/crond`
      echo $PID >/var/run/crond.pid
      add_daemon crond
      stat_done
    fi
    ;;
  stop)
    stat_busy "正在关闭 Cron 后台服务"
    [ ! -z "$PID" ]  && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon crond
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
