#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

if [ "${msg_lang}" = "cn" ]; then
	stat_busy "解析 policykit权限设置"
else
	stat_busy "Parsing groups for policykit handling"
fi
export storage_users=$(cat /etc/group | grep -i storage | cut -d ':' -f 4 | sed 's/,/|/')
export power_users=$(cat /etc/group | grep -i power | cut -d ':' -f 4 | sed 's/,/|/')
stat_done
exit 0