#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
case "$1" in
  start)
	if [ "${msg_lang}" = "cn" ]; then
		stat_busy "启动 wicd后台守护进程"
	else
		stat_busy "Starting wicd Daemon"
	fi
    pkill -f wicd-daemon.py &> /dev/null
    /usr/sbin/wicd &> /dev/null
    add_daemon wicd
    stat_done
    ;;
  stop)
	if [ "${msg_lang}" = "cn" ]; then
		stat_busy "关闭 wicd后台守护进程"
	else
		stat_busy "Stopping wicd Daemon"
	fi
    pkill -f wicd-daemon.py &> /dev/null
    rm_daemon wicd
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
