#!/bin/sh

#
# ~/.xinitrc
# 字体分辨率
XRESOURCES=`mktemp /tmp/xrdb.XXXXXX`
cat >> $XRESOURCES << EOF
Xft.dpi: 96
Xft.hinting: 1
Xft.hintstyle: hintmedium
EOF

export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
export XMODIFIERS="@im="fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"

xrdb -nocpp -merge $XRESOURCES
rm -f $XRESOURCES

#/usr/share/dropbox/dropbox &

#exec /etc/X11/xinit/xinitrc.fluxbox
exec /etc/X11/xinit/xinitrc.openbox
#exec /etc/X11/xinit/xinitrc.lxde
#exec /etc/X11/xinit/xinitrc.icewm
#exec /etc/X11/xinit/xinitrc.awesome
#exec fvwm2
