#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
	if [ "${msg_lang}" = "cn" ]; then
		stat_busy "正在启动 ADSL宽带拨号"
	else
		stat_busy "Starting ADSL Connection"
    fi
    /usr/sbin/pppoe-start &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon adsl
      stat_done
    fi
    ;;
  stop)
	if [ "${msg_lang}" = "cn" ]; then
		stat_busy "正在关闭 ADSL宽带连接"
	else
		stat_busy "Stopping ADSL Connection"
	fi
    /usr/sbin/pppoe-stop &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon adsl
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
