#!/bin/bash

# sourcing our current rc.conf requires this to be a bash script
. /etc/rc.conf
. /etc/rc.d/functions

rc=0

case "$1" in
	start)
		if [ "${msg_lang}" = "cn" ]; then
			stat_busy "挂载 网络文件系统"
		else
			stat_busy "Mounting Network Filesystems"
		fi
		/bin/mount -a -t nfs,nfs4,smbfs,codafs,ncpfs,cifs,shfs,glusterfs,fuse,fuseblk,fuse.glusterfs
		rc=$?
		/bin/mount -a -O _netdev
		rc=$(($rc+$?))
		if [ $rc -gt 0 ]; then
			stat_fail
		else
			add_daemon netfs
			stat_done
		fi
		;;
	stop)
		if [ "${msg_lang}" = "cn" ]; then
			stat_busy "卸载 网络文件系统"
		else
			stat_busy "Unmounting Network Filesystems"
		fi
		/bin/umount -a -O _netdev
		rc=$?
		/bin/umount -a -t nfs,nfs4,smbfs,codafs,ncpfs,cifs,shfs,glusterfs,fuse,fuseblk,fuse.glusterfs
		rc=$(($rc+$?))
		if [ $rc -gt 0 ]; then
			stat_fail
		else
			rm_daemon netfs
			stat_done
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"  
esac

# vim: set ts=2 noet:
