#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/syslog-ng`
case "$1" in
  start)
	if [ "${msg_lang}" = "cn" ]; then
		stat_busy "正在启动 系统日志程序Syslog-NG"
	else
		stat_busy "Starting Syslog-NG"
	fi
    [ -z "$PID" ] && /usr/sbin/syslog-ng
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon syslog-ng
      stat_done
    fi
    ;;
  stop)
	if [ "${msg_lang}" = "cn" ]; then
		stat_busy "正在关闭 系统日志程序Syslog-NG"
	else
		stat_busy "Stopping Syslog-NG"
	fi
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /var/run/syslog-ng.pid
#     Removing stale syslog-ng.persist file. It's new location, as of 2.0.6-1, is /var/lib/syslog-ng/
      rm -f /var/syslog-ng.persist
      rm_daemon syslog-ng
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
